blank_issues_enabled: false
contact_links:
  - name: 💬 Вопросы и обсуждения
    url: https://github.com/jrfrigat/YandexMusic/discussions
    about: Для вопросов по использованию используйте Discussions.
