using System.Text.Json.Serialization;
using YandexMusic.Serialization;

namespace YandexMusic.Ynison;

/// <summary>Descriptive information about a device.</summary>
/// <param name="DeviceId">The device identifier.</param>
/// <param name="Title">The human-readable device name.</param>
/// <param name="Type">The device type.</param>
/// <param name="AppName">The client application of the device.</param>
/// <param name="AppVersion">The version of the client application.</param>
public sealed record DeviceInfo(
    string DeviceId,
    string Title,
    DeviceType Type,
    string AppName,
    string AppVersion = "");

/// <summary>What a device can do in a Ynison session.</summary>
/// <param name="CanBePlayer">Whether the device can be active and play entities.</param>
/// <param name="CanBeRemoteController">Whether the device can act as a remote controller.</param>
/// <param name="VolumeGranularity">
/// The number of steps on the device's volume scale; 0 means remote volume control is unsupported.
/// Valid range is [0, 1000].
/// </param>
public sealed record DeviceCapabilities(
    bool CanBePlayer,
    bool CanBeRemoteController,
    int VolumeGranularity = 0);

/// <summary>The volume state of a device.</summary>
/// <param name="Volume">The volume in [0.0; 1.0].</param>
/// <param name="Version">The version of the last volume change.</param>
public sealed record DeviceVolume(double Volume, UpdateVersion? Version = null);

/// <summary>The connection session of a device; unique per initialized connection.</summary>
/// <param name="Id">The session id; generated by the server.</param>
public sealed record DeviceSession(
    [property: JsonConverter(typeof(ProtoInt64Converter))] long Id);

/// <summary>A device known to the current Ynison session, including offline ones.</summary>
/// <param name="Info">The device information.</param>
/// <param name="Volume">The legacy volume value; see <paramref name="VolumeInfo"/>.</param>
/// <param name="Capabilities">The device capabilities.</param>
/// <param name="Session">The connection session.</param>
/// <param name="IsOffline">Whether the device is currently disconnected from Ynison.</param>
/// <param name="VolumeInfo">The volume state together with its change version.</param>
public sealed record Device(
    DeviceInfo? Info,
    double Volume = 0,
    DeviceCapabilities? Capabilities = null,
    DeviceSession? Session = null,
    bool IsOffline = false,
    DeviceVolume? VolumeInfo = null);

/// <summary>The device description a device sends about itself when registering.</summary>
/// <param name="Info">The device information.</param>
/// <param name="Volume">The legacy volume value; see <paramref name="VolumeInfo"/>.</param>
/// <param name="Capabilities">The device capabilities.</param>
/// <param name="VolumeInfo">The volume state.</param>
public sealed record UpdateDevice(
    DeviceInfo? Info,
    double Volume = 0,
    DeviceCapabilities? Capabilities = null,
    DeviceVolume? VolumeInfo = null);
